### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by ghost** [michidk/SimpleTwitchHelper#1]
In the project are some absolute paths like "....\TwitchCSharp\TwitchCSharp\bin\Release\Newtonsoft.Json.dll" and "C:\Users\michi\Documents\Visual Studio 2015\Projects\SimpleTwitchHelper\SimpleTwitchHelper\Build\". So the project is unbuildable for other than you.

**Comment by michidk** [comment]
Just remove and re-add the needed assemblies. If the problem persists, send me the name of the files, and the line number, containing these absolute paths.

**Comment by ghost** [comment]
e.g. https://github.com/michidk/SimpleTwitchHelper/blob/master/SimpleTwitchHelper/SimpleTwitchHelper.csproj#L18 and https://github.com/michidk/SimpleTwitchHelper/blob/master/SimpleTwitchHelper/SimpleTwitchHelper.csproj#L71

Don't want to have an "TwitchCSharp" directory in my folder, where is only an DLL, You should embed the DLLs in the root folder of the project and not in folders that are not in the project included.

**Comment by michidk** [comment]
The first one is irrelevant. (Read more: https://msdn.microsoft.com/en-us/library/c37e68bc.aspx)
For the second one, i will change the path, but keep in mind that i don't upload the assemblies.
You can download them here:
https://github.com/michidk/TwitchCSharp/releases
https://github.com/michidk/SimpleLoggingSystem/releases
https://github.com/michidk/SimpleConfigurationSystem/releases

These were installed with NuGet:
https://github.com/aaubry/YamlDotNet/releases 
http://www.newtonsoft.com/json
http://restsharp.org

I will upload this version later.

**Comment by michidk** [comment]
Fixed in https://github.com/michidk/SimpleTwitchHelper/commit/0dc547e056ab53c57752fbb031f9255adb6ad719
