### ISSUE TITLE
No Form designer in thise code?

### ISSUE THREAD

**Issue by BeansSi** [michidk/SimpleTwitchHelper#2]
Hello,

i am looking for the form designer in this source code, but i cant find it?

Regards

**Comment by michidk** [comment]
SimpleTwitchHelpers doesn't use the form designer.. Its uses the Windows Presentation Framework (https://de.wikipedia.org/wiki/Windows_Presentation_Foundation)

The wpf windows are here: https://github.com/michidk/SimpleTwitchHelper/tree/master/SimpleTwitchHelper/Windows
